- name: Deploy Node.js App
  hosts: web
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true
    - name: Pull Docker image
      docker_image:
        name: yourdockerhubusername/myapp
        source: pull
    - name: Run container
      docker_container:
        name: myapp
        image: yourdockerhubusername/myapp
        state: started
        ports:
          - "80:3000"
